name: simpegPF

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - dask
  - zarr
  - pip
  - git
  - properties
  - pip:
    - discretize
    - git+https://github.com/simpeg/simpeg.git@MagDev_DF_Dask
